### ISSUE TITLE
Make it discoverable on the charm store

### ISSUE THREAD

**Issue by thammegowda** [buggtb/solr-charm#2]
When we search for `solr` or `Solr` on jujucharms, this one doesn't show up in search results!

Test:
https://jujucharms.com/q/solr

**Comment by buggtb** [comment]
their search sucks try apache-solr

**Comment by buggtb** [comment]
also the sparkler bundles will deploy it all for you also

**Comment by thammegowda** [comment]
> their search sucks try apache-solr

Got it. Thanks
